In [1]:
import numpy as np
from numpy.polynomial.polynomial import polyval

#### $3x^2+2X+1$

In [2]:
polyval(2, [1, 2, 3])

17.0

In [3]:
polyval(1, [1,2,3])

6.0

#### $x^2+2X+3$

In [4]:
polyval(2, [3,2,1])

11.0

In [5]:
polyval(2, [1,2,3])

17.0

In [6]:
p=np.arange(4).reshape(2,2)    #EQUATION BY USING AXIS=COLUMNs
p

array([[0, 1],
       [2, 3]])

## Eq:2x

# Eq:3x+1

In [7]:
polyval([1,2],p,tensor=True)

array([[2., 4.],
       [4., 7.]])

In [8]:
polyval([1,2],p,tensor=False)

array([2., 7.])

In [9]:
First_Degree=np.poly1d([1,2,3])
print(First_Degree)

   2
1 x + 2 x + 3


In [10]:
First_Degree.coefficients

array([1, 2, 3])

In [11]:
First_Degree.coef

array([1, 2, 3])

In [12]:
First_Degree.coeffs

array([1, 2, 3])

In [13]:
First_Degree.roots

array([-1.+1.41421356j, -1.-1.41421356j])

In [14]:
First_Degree.order

2